import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/app/_fonts/fonts";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${inter.className} mx-[calc(1.75rem-1rem)] my-7 overflow-hidden text-sm md:mx-7`}
         >
            {children}
         </body>
      </html>
   );
}
